Add controllers
Kiril1KinG/java-shareit pull request #1
Opened 2024-01-10 20:05 UTC by Kiril1KinG

Увлекся и залез в букинги с реквестами, поэтому просьба не обращать внимания)
PS: не могу ответить на тот твой коммент, но смысл данного описания был в том, что реквесты и букинги не требуются по тз, а я там немножко сервисы и тд накидал) Даже в тудушке там была указанная другая ветка разработки уже, на что я не обратил внимание, в данном тз нужны только айтемы и юзеры

2024-01-11 16:57 UTC, kalitva requested changes

2024-01-11 16:57 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +@RequestMapping(path = "/bookings")
`@RequestMapping("/bookings")`

2024-01-11 16:57 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/dto/BookingRequest.java
> + */
Удали эти комменты

2024-01-11 16:57 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    Booking update(int id, Booking booking);
Давай засетим айдишник в букинг перед передачей в сервис, и удалим параметр метода `id`

2024-01-11 16:57 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/storage/BookingStorage.java
> +    Booking update(int id, Booking booking);
То же самое, принимай только параметр объекта `Booking`

2024-01-11 16:57 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final ItemMapper mapper;
Мы же выше вызывали мапперы в контроллерах, так что в этом случае давай также мапить в контроллере

2024-01-11 16:57 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Collection<ItemResponse> items = itemStorage.getAll().stream()
Перенеси логику поиска (стрим) в сторадж

2024-01-11 16:57 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public Collection<ItemResponse> getAllForOwner(int userId) {
`getAllForOwner --> getByOwner`

2024-01-14 08:45 UTC, kalitva commented
> Увлекся и залез в букинги с реквестами, поэтому просьба не обращать внимания)

Давать описания а ПР - хорошая практитка. Но если оставляешь описание, напиши больше деталей - что конкретно сделано с букингами и реквестами и почему

2024-01-14 08:47 UTC, kalitva commented
Отлично, что даешь краткие и содержательные описания коммитов и даже с префиксами. Наверное, было бы лучше по умолчанию делать их на английском, пока в конкретном проекте нет договоренности делать на русском

2024-01-14 08:56 UTC, kalitva requested changes

2024-01-14 08:56 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public boolean equals(Object o) {
Если объект не используется сетах или хэшмапах, то не вижу необходимости переопределять `equals` и `hashCode`

2024-01-14 08:56 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new DataNotExistsException(String.format("Get booking by id filed, booking with id %d not exists",
Лучше форматировать как-то так

```java
throw new DataNotExistsException(
            String.format("Get booking by id filed, booking with id %d not exists",  id));
```

2024-01-14 08:56 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Collection<Booking> bookings = bookingStorage.getAll();
Лучше

```java
    public Collection<Booking> getAll() {
        return bookingStorage.getAll();
    }
```

Ты же уже логировал в контроллере, что пришел реквест, информация не самая полезная (потому что, если запрос успешен, данные есть в респонсе, если была ошибка в при вытягивании из стораджа, до логирования исполнение и не дойдет)

2024-01-14 08:56 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/storage/BookingStorage.java
> +    Booking update(int id, Booking booking);
Почему не сделано и при этом коммент отмечен как resolved?

2024-01-15 00:04 UTC, Kiril1KinG commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Collection<Booking> bookings = bookingStorage.getAll();
Тут не совсем понимаю замечание. Вот лично мне - удобно, когда видно какие объекты внутри, по логам при отладке, потому что без них вообще не понятно чо там происходит, нормальный там объект или че-то не так работает как по задумке, а так видно, что вот он запрос GET и вот они объекты в консоли, легко читать такой лог и понимать где ошибка без возни с отладчиком, и сравниваешь с тестами постмана просто - вкусовщина.
PS: поменял описание ПР, а то все 3 замечания по букингу)

2024-01-15 18:17 UTC, kalitva requested changes

2024-01-15 18:17 UTC, kalitva commented on pom.xml
> +		<!--  lookup parent from repository  -->
Удали коммент

2024-01-15 18:17 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +
Лишняя пустая линия

2024-01-15 18:17 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Collection<Booking> bookings = bookingStorage.getAll();
Окей

2024-01-17 19:54 UTC, kalitva approved these changes

2024-01-17 19:54 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemResponse add(@RequestHeader("X-Sharer-User-Id") Integer userId, @RequestBody @Valid ItemCreateRequest request) {
Давай `X-Sharer-User-Id` вынесем в константу

2024-01-17 19:54 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/dto/ItemUpdateRequest.java
> +
Лишняя пустая линия

2024-01-17 19:54 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            throw new DataNotExistsException(
`DataNotExistsException --> DataDoesNotExistException`

2024-01-17 19:54 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Collection<Item> items = itemStorage.getAll().stream()
Перенеси этот стрим в сторадж

2024-01-17 19:54 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            throw new RuntimeException(
Нежелательно использовать `RuntimeException`, выбрасывай свой `DataNotExistsException`

2024-01-17 19:54 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        if (allUsersWithoutThis.stream().map(User::getEmail).anyMatch(p -> p.equals(user.getEmail()))) {
Создай в сторадже метод `existsByEmail` , перенеси туда стрим и вызывай этот метод здесь

2024-02-01 13:40 UTC, merged