Add bookings
Kiril1KinG/java-shareit pull request #2
Opened 2024-02-08 20:14 UTC by Kiril1KinG

2024-02-08 23:31 UTC, kalitva requested changes

2024-02-08 23:31 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/Entity/BookingEntity.java
> +@EqualsAndHashCode
Не думаю, что есть необходимость ставить `EqualsAndHashCode` если не используешь объект в хэшмап или в хэшсет

2024-02-08 23:31 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/Entity/BookingEntity.java
> +@ToString
Тоже `ToString` точно нужен?

2024-02-08 23:31 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +
Лишняя пустая линия

2024-02-08 23:31 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    private void checkBookingRequestTime(BookingRequest request) {
Давай эту валидацию перенесем в сервис

2024-02-08 23:31 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/dto/BookingShort.java
> +
Лишняя пустая линия

2024-02-08 23:31 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (strState == null) {
```java
        if (strState == null) {
            return BookingState.ALL;
        }
        try {
            return BookingState.valueOf(strState.toUpperCase());
        } catch (IllegalArgumentException e) {
            throw new UnknownStateException("Unknown state: " + strState);
        }
    }
```

Ненужный else

2024-02-08 23:31 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/storage/BookingRepository.java
> +    Collection<BookingEntity> findAllByBooker_IdOrderByStartDesc(Integer bookerId);
`findAllByBooker_IdOrderByStartDesc --> findAllByBookerIdOrderByStartDesc`

Не используй андерскор в именах методов (для всех методов репозиториев)

2024-02-08 23:31 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/storage/BookingRepository.java
> +
Лишняя пустая линия, проверь везде

2024-02-08 23:31 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/storage/BookingRepository.java
> +}
Вместо определения всех этих методов для фильтрации объектов можно воспользоваться `Specification`, попробуй, это используется почти везде, где есть spring data

https://spring.io/blog/2011/04/26/advanced-spring-data-jpa-specifications-and-querydsl

2024-02-08 23:31 UTC, kalitva commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        return e;
Не следует возвращать исключение из контроллеров, возвращай лучше хэшмап как в остальных

2024-02-08 23:31 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/storage/ItemRepository.java
> +            "where (upper(i.name) like upper(concat('%', ?1, '%')) " +
`"where (upper(i.name) like upper(concat('%', :text, '%')) "`

Избегай индексов, обращайся к параметрам по имени

2024-02-08 23:31 UTC, kalitva commented on src/main/resources/schema.sql
> +drop table if exists comments, requests, bookings, items, users;
Не очень хорошая сносить бд при каждом запуске приложения, подумай как этого избежать

2024-02-08 23:31 UTC, kalitva commented on src/main/resources/schema.sql
> +	id BIGINT not null default nextval('requests_id_seq'),
Пожалусйта, везде отступы по 4 пробела

2024-02-09 18:02 UTC, Kiril1KinG commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        return e;
Отсавляю как есть, тесты не пройдут, обсуждали в лс

2024-02-09 18:03 UTC, Kiril1KinG commented on src/main/java/ru/practicum/shareit/booking/Entity/BookingEntity.java
> +@ToString
Используется в логах, пока оставлю

2024-02-09 18:57 UTC, Kiril1KinG commented on src/main/java/ru/practicum/shareit/booking/storage/BookingRepository.java
> +}
Обязательно потрогаю, может как раз на 15ФЗ, сейчас просто уже прохожу параллельно другой спринт, отстал нехило, уже надо 16ФЗ к ЖД сдавать, пока оставил так, надеюсь сейчас остальные быстро накатаю)

2024-02-10 16:44 UTC, kalitva approved these changes

2024-02-10 16:44 UTC, kalitva commented on pom.xml
> +			<artifactId>hibernate-core</artifactId>
Разве этого нет в spring-data-jps-starter?

2024-02-10 16:44 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                                     @RequestParam(value = "state",
Обязательно указывать `value`?

2024-02-10 16:44 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/dto/BookingShort.java
> +public class BookingShort {
`BookingShort --> BookingShortDto`

2024-02-10 16:44 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private static BookingState filterBookingState(String strState) {
`strState --> state`

2024-02-10 16:44 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/Entity/BookingEntity.java
> +package ru.practicum.shareit.booking.Entity;
Пожалуйста, имя пакета всегда с маленькой буквы

2024-02-10 16:44 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>  public class Booking {
Может, имеет смысл сделать объект имутабельным, раз разделяешь модели и ентити

2024-02-10 16:44 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Optional<BookingEntity> bookingEntity = bookingRepository.findById(bookingId);
```java
BookingEntity bookingEntity = bookingRepository.findById(bookingId)
        .orlseThrow(() -> new DataDoesNotExistsException(...
```

Погугли как следует использовать `Optional` (поправь все подобные кейсы)

2024-02-12 13:53 UTC, Kiril1KinG commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                                     @RequestParam(value = "state",
![image](https://github.com/Kiril1KinG/java-shareit/assets/122753294/46b8936d-17b0-4106-813f-0513f3242ea2)
Да, там два параметра, поправил перенос

2024-02-12 14:59 UTC, merged