Add item requests
Kiril1KinG/java-shareit pull request #3
Opened 2024-02-14 17:12 UTC by Kiril1KinG

2024-03-01 09:22 UTC, kalitva requested changes

2024-03-01 09:22 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    Collection<Booking> getAllBookingsByState(Integer userId, String bookingState, Integer from, Integer size);
Принимай вместо `from` и `size` сразу `Pafeable`

2024-03-01 09:22 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (from != null && size != null) {
Избавься от этой проверки (можешь с помощью аннотации `@NotNull` или принимай примитивы)

2024-03-01 09:22 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            return PageRequest.of(from > 0 ? from / size : 0, size, sort);
А зачем проверять `from > 0`?

2024-03-01 09:22 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/storage/BookingRepository.java
>                                                                      BookingStatus bookingStatus, LocalDateTime now);
Вместо определения всех этих методов для фильтрации объектов можно воспользоваться `Specification`, попробуй, это используется почти везде, где есть spring data

https://spring.io/blog/2011/04/26/advanced-spring-data-jpa-specifications-and-querydsl

2024-03-01 09:22 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/entity/CommentEntity.java
> +@NoArgsConstructor
Зачем эти конструкторы?

2024-03-01 09:22 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (from == null ^ size == null) {
Пожалуйста, давай без битовых операторов

2024-03-01 09:22 UTC, kalitva commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                .andExpect(jsonPath("[1].item.name").value("item2"));
Возможно, лучше использовать `ObjectMapper` чтобы сравнивать json'ы

2024-03-01 09:22 UTC, kalitva commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +        Assertions.assertEquals(List.of(booking),
Обычно ассерты импортируют используя `import sattic`

2024-03-01 14:58 UTC, Kiril1KinG commented on src/main/java/ru/practicum/shareit/item/entity/CommentEntity.java
> +@NoArgsConstructor
Конструкторы добавил практически везде, AllArgs преимущественно для тестов, чтобы бы не сетить, поскольку это было бы просто оч громоздко и не удобно, конструктор намного лаконичнее, а NoArgs стал нужен поскольку без него ругатся хибернейт, видимо потому что создаёт пустые объекты и маппит их сеттерами где-то под капотом.

2024-03-01 15:03 UTC, Kiril1KinG commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (from == null ^ size == null) {
Чем плох битовый оператор? Я про него случайно вспомнил, когда строил логическое выражение, потому что XOR здесь как никогда кстати, по другому можно только заменить как-то так:
`if (froml == null & size != null) & (from == null & size != null)) `, 
по-моему через исключающее или намного легче воспринимается

2024-03-01 15:16 UTC, Kiril1KinG commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                .andExpect(jsonPath("[1].item.name").value("item2"));
Первый раз услышал о таком методе, я так понял ты имеешь в виду использовать встроенную сериализацию и десереализацию и сравнивать через assertEquals? Пока не вижу принципиальной разницы, делал как было в примерах из спринта с MockMvc

2024-03-01 15:21 UTC, Kiril1KinG commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +        Assertions.assertEquals(List.of(booking),
Да, при создании тестов автоматом создается статический импорт всей библиотеки, как по мне - излишество, я в большинстве случаев использую только assertEquals и assertTrue, так же можно было и с мокито поступить, но вроде как статики не есть хорошо, или я ошибаюсь? В любом случае когда мало знаешь фрейм через точечную нотацию как-то легче было читать, статиками можно внести смуты какой метод откуда)

2024-03-01 15:23 UTC, Kiril1KinG commented on src/main/java/ru/practicum/shareit/booking/storage/BookingRepository.java
>                                                                      BookingStatus bookingStatus, LocalDateTime now);
Да, я  помню про спецификации еще с прошлого спринта, я их так и не трогал и сейчас не оч хочу самостоятельно, потому что нам там обещали как раз показать QueryDsl на следущем QA, чтобы можно было разобрать вместе с наставником)

2024-03-01 15:38 UTC, Kiril1KinG commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            return PageRequest.of(from > 0 ? from / size : 0, size, sort);
Сам не вдуплил, но как я понял при формировании `PageRequest.of(...)` первый параметр называется page, и по видимому это означает номер страницы, в том смысле, что если сайз 6 а страница 4 то это значит, что до этого было 3 страницы, которые также 3*6 объектов и начинаться всё должно с объекта с индексом 19, а по тз у нас не страницы а просто индексы с какого по какой объект, тут просто принцип разный видимо, соответственно эта штука просто вычисляет корректный номер страницы при заданных параметрах, а при нуле работает корректно

2024-03-01 15:42 UTC, Kiril1KinG commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (from != null && size != null) {
Может я что-то не понимаю, но вроде здесь не аннотация не примитив не поможет, потому что по тз метод остается тот же, только теперь он принимает ещё два параметра, которых может и не быть, а если их нет то возвращаются все объекты без пагинации, поэтому мне нужно знать null они или нет, чтобы сформировать ответ либо с пагинацией либо без

2024-03-01 17:39 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (from != null && size != null) {
Я решал это задание и помню, что обошелся без этого (но не помню как именно). Возможно, используя дефолные принимая параметры в контроллере

2024-03-01 17:40 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            return PageRequest.of(from > 0 ? from / size : 0, size, sort);
Ну если `from` 0 его разделить на любое число, то получется же тоже 0, я про это

2024-03-01 17:41 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/storage/BookingRepository.java
>                                                                      BookingStatus bookingStatus, LocalDateTime now);
А, точно

2024-03-01 17:46 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/entity/CommentEntity.java
> +@NoArgsConstructor
Я бы посоветовал использовать в тестах методы для создания объектов (можешь выделить для этого утилитный класс в каталоге тестов). Правило такое - мы можем (и должны) рефакторить класс под то, чтобы его можно тестить, (делать его более модульным, упрощать условия, избавляться от статики и т.д.). Но подстраиваться под тесты классы не должны - то есть не следует делать например приватный метод публичным, создавать дополнительные поля и методы, в том числе создавать конструкторы для удобства

2024-03-01 17:47 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (from == null ^ size == null) {
Тем что их не все знают\помнят, только по этому

2024-03-01 17:48 UTC, kalitva commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                .andExpect(jsonPath("[1].item.name").value("item2"));
Создаешь expected объект, преобразуешь его с помощью `ObjectMapper` и сравниваешь одним ассертом вместо того, чтобы проверять filed by field

2024-03-01 17:54 UTC, kalitva commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +        Assertions.assertEquals(List.of(booking),
Согласен про то, что они читаются хуже, но в тестах (только в тестах) принято ассерты импортировать статическими импортами. Мокито это тоже касается

Нужно знать и придерживаться общепринятых практик, они помогают тем кто пишет и читает код лучше друг друга понимать

2024-03-02 15:17 UTC, Kiril1KinG commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                .andExpect(jsonPath("[1].item.name").value("item2"));
Я оставлю так потому что в MockMvc тут свои плюсы, через сериализацию и ассерт это очень топорная проверка, а в MockMvc куча матчеров и тд под разные проверки, например в каких-то тестах я не привязывавлся к конкретному значению а просто проверял что hasJsonPath() или exists(), думаю вкусовщина

2024-03-02 19:35 UTC, Kiril1KinG commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (from != null && size != null) {
Я понял о чем ты говорил, действительно да, проверка лишняя) Можно просто from / size

2024-03-02 19:39 UTC, Kiril1KinG commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            return PageRequest.of(from > 0 ? from / size : 0, size, sort);
Я понял о чем ты говорил, действительно да, проверка лишняя) Можно просто from / size

2024-03-02 19:58 UTC, Kiril1KinG commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (from != null && size != null) {
![image](https://github.com/Kiril1KinG/java-shareit/assets/122753294/9785a3a2-cd50-4b1b-8a80-1a4b8c04a4f1)
Не знаю как тут можно отказаться от проверки на null, потому что в случае присутствия и отсутствия параметров пагинации `Pageable`  формируется по разному

2024-03-02 20:00 UTC, Kiril1KinG commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (from != null && size != null) {
Думал прокинуть метод репозитория count и засунуть его в defaultValue в контроллере, что бы фром по дефолту был 0, а сайз вычисляемый, но оно принимает только константы, что в давном случае невозможно

2024-03-02 20:02 UTC, Kiril1KinG commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    Collection<Booking> getAllBookingsByState(Integer userId, String bookingState, Integer from, Integer size);
Писал в пачке, что в контроллере Pageable определять будет тумач, думаю вынести не получиться, что бы не смешивать архитектурные слои, возможно правда намудрил

2024-03-03 19:08 UTC, kalitva approved these changes

2024-03-03 19:08 UTC, kalitva commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                .andExpect(jsonPath("[1].item.name").value("item2"));
Вкусовщина? То что ты пишешь в 15 строчек, а я предлагаю заменить одной это вопрос вкусовщины? (Ассерт имелось ввиду использовать `MockMvc`. `andExpect` например это тоже ассерт)

2024-03-03 19:08 UTC, kalitva commented on src/test/java/ru/practicum/shareit/classBuilder/UserBuilder.java
> +public class UserBuilder {
Билдером назвать некорретно, назови например `UserTestDataProvider` или `TestUserProvider` или что-то типа того

2024-03-03 19:09 UTC, kalitva commented
Принято

2024-03-07 12:37 UTC, merged